### ISSUE TITLE
Incorrect image path

### ISSUE THREAD

**Issue by nwithan8** [UNRA1DUser/unraid-docker-templates#1]
https://github.com/UNRA1DUser/unraid-docker-templates/blob/a0d4a2dabdb02b7e44593899694848acb6c6a64b/UNRA1DUser/ca_profile.xml#L3

`images` should be `img` in the image path

**Comment by UNRA1DUser** [comment]
Hi @nwithan8,

thanks for that! I renamed the folder today and forgott to change the Icon link in this file.
Changed it now.
