### ISSUE TITLE
Please don't use "official" if you're using other people templates

### ISSUE THREAD

**Issue by martabal** [UNRA1DUser/unraid-docker-templates#4]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

-

### Link to documentation

-

### Link to source code

-

**Comment by martabal** [comment]
Hey man, I know it's FOSS and the licenses allow you to redistribute the files however you want.

But at least, I suggest you to be clear about the name. I don't really see the point of this template, Imagegenius already has its "official" template which is automatically generated by the CI so always up to date with the image. Adding the same templates in the CA is just misleading, it harms the community more than anything else.

Additionally, adding your own paypal link when the template is not yours is not very cool...

**Comment by UNRA1DUser** [comment]
Hey, you're right. I'm really sorry about that. I'm quiet new to this. I've only changed a few small things, but that doesn't require a new template. I will delete my template.

Thanks for that and sorry again.

**Comment by martabal** [comment]
Thank you, I think that's the best move.

If you're new, let me give you some recommendations:
- Don't use the "Official" term unless you are maintainer of the project. For example, immich from Imagegenius is an AIO container for Immich which, if you use the official way to install it, requires multiple containers. It's a community project and not the "official" way to install Immich.
-  Avoid using templates which already exists: If I reached you, it's because someone was confused about which template to use to install Immich. Adding more templates when they already exist is not really helpful. IMO, you should first contribute to already existing templates and if they are no longer maintained, then yes, it sounds reasonable to publish your own template.

Again, thank you for your understanding and your reactivity !
