### ISSUE TITLE
You've copied someone else's templates without permission

### ISSUE THREAD

**Issue by bo0tzz** [UNRA1DUser/unraid-docker-templates#5]
### Application does not already exist

- [X] I have verified that the requested application template does not already exist in Community Apps, or that the existing Community App template is out of date and no longer maintained.

### Application is actively supported

- [X] I have verified that the requested application is actively maintained.

### Link to Docker Hub or GitHub Container Registry

-

### Link to documentation

-

### Link to source code

-

**Comment by bo0tzz** [comment]
Your repository contains some template files that were copied from elsewhere and edited, without permission or an appropriate license. For example, your Immich template is an edited version of the [imagegenius template](https://github.com/imagegenius/templates/blob/main/unraid/immich.xml). This is evidenced for example by the identical descriptions for env vars.

The imagegenius template repository does not have a license file, and thus does not grant any permission for you to copy or redistribute their templates. The repository that they generate their templates from (https://github.com/imagegenius/docker-immich) is licensed under GPLv3, so if that were the license that applies then you are relicensing that to MIT, which is not allowed.

Please rectify this as soon as possible. For upstream templates that do not have a license, either remove your copy or get permission from the original authors. For those that do, make sure the license you use on this repository is appropriately matched.

**Comment by UNRA1DUser** [comment]
Hey, I'm really sorry about that. I'm quiet new to this. I will delete my template.

**Comment by bo0tzz** [comment]
Thank you for the reasonable response, and sorry for the harsh comment ;)
